[package]
name = "Stash"
version = "0.1.0"
upgrade_policy = "compatible"

[addresses]
stash = "_"

[dev-addresses]
stash = "0xcafe"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
